### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by karneaud** [KeithNdhlovu/laravel-sso-tenancy#1]
Hi. I was researching using laravel/ laravel passport to create my own custom identity prodivder and SSO client and stumbled upon your repo. Do you have any articles on this that you can share with me?

**Comment by KeithNdhlovu** [comment]
Hi @karneaud thanks for taking interest in my project, this is still a work in progress and i am planning to document this in the next coming weeks as i have implemented it in one of my other projects with success. I will either share a wiki or a Notion doc regarding implementation.

**Comment by karneaud** [comment]
@KeithNdhlovu thanks for this. I myself have a project I need to implement however the environment differs as I have non-laravel apps to consider. I look forward to your articles and insights.
